---

- hosts: all
  connection: local
  gather_facts: False

  tasks:

    - name: Decom OCP Environment
      ec2:
         state: 'absent'
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         region: "{{ aws_region }}"
         instance_ids: "{{ ec2_id }}"
      delegate_to: "localhost"

    - name: Refresh EC2 cache
      command: /etc/ansible/ec2.py --refresh-cache
    - name: Refresh in-memory EC2 cache
      meta: refresh_inventory
