---

###########################################################################
### OpenShift Master Vars
###########################################################################

openshift_master_api_port: 443  
openshift_master_console_port: 443

openshift_master_cluster_method: 'native'
openshift_master_cluster_hostname: 'lb.phmcmahon.com'
openshift_master_cluster_public_hostname: 'loadbalancer.phmcmahon.com' 
openshift_master_default_subdomain: 'apps.phmcmahon.com' 

# Set this line to enable NFS
openshift_enable_unsupported_configurations: True
